import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"prueba",
            artist: "60's",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://dc603.4shared.com/img/zklG_eotea/84b84ce1/dlink__2Fdownload_2FzklG_5Feotea_2FLord_5FShiva_5FRingtones_5FTelugu_5FNa.mp3_3Fsbsr_3D34d0e33645d5431ccb122386021fe969ab5_26bip_3DMTgxLjU4LjM5LjEwNg_26lgfp_3D52_26bip_3DMTgxLjU4LjM5LjEwNg/preview.mp3",
            active: true,
        },
        {
            name:"el otro",
            artist: "Lounge",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://dc687.4shared.com/img/0njwtQlOea/8243a0ba/dlink__2Fdownload_2F0njwtQlOea_2FTelugu_5F4.mp3_3Fsbsr_3Da1868aa2fb49d500d014cfa3cf6fa508ab5_26bip_3DMTgxLjU4LjM5LjEwNg_26lgfp_3D52_26bip_3DMTgxLjU4LjM5LjEwNg/preview.mp3",
            active: false,
        },
        {
            name:"prueba 2",
            artist: "70's",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://public.sn.files.1drv.com/y4mOMYrD4q7HFVdWSPutassNGUMZrGs14fjh70LfnJGq8QeDNW0f9b1-dY0WbROZqfpcZStMJaLLaO3gAAdsIf4a6VSak53oCgDtJ5dImd0xZCFPDfyKXk8ULygxer1G-6tmd7HjXxEJ-TpTgLKEpNZly4BY13NHcqOY5mlK-of6f-zX8QhLRj2Wh_CqxgRj728FoG1baMqAq4gy5tf-OBOMbB-6XSeO2eag6hZAMn4JGI?",
            active: false,
        },
        {
            name:"prueba 3",
            artist: "80's",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://public.sn.files.1drv.com/y4mrxNqmxaD0ilxDLkLlfWgDInQftwvzWwRtpNkK9-z2Rd_AY8H-71m8Z7e4PQ78T9WKIBlbWIXJ0_10t-6-00BiyKSiRRvbxCbcsN2w-9SdtXkvH-B3agnu_Xwx2io_HPWhs2VYp1l4PatdTp3dG42L_vko6C09NrSnLNA-QYRAzalE9aaymH5A8rz3-vLu3JE6zFoWg0ZUP0uy9NUYFQW4g32tk-jsX9F30MXI9p4DxA?",
            active: false,
        },
        {
            name:"prueba 4",
            artist: "Lounge",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://public.sn.files.1drv.com/y4m7XwizrTYbfGJfFPnzYXolK_nQOS-TNJ7Julw-9e3IMDln3MHw6pERt7-ShA85gd3Q-zGgrtfzghmg4fskcyF38oyNUVqkX380Q7kqpOqtpdMEYlacspgFq0hQxc5KtvhmXhE9oZk0olplaYtRcmB50rUiW8oRSSahYkYu8-uGWt7b2Ps2mhEmW2rRPny3jI9XVMO_TAzBB_9f3kflNBIpiXLo4kQlpafSnsXK13YKKQ?",
            active: false,
        },
        {
            name:"FFH The 90's",
            artist: "90's",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "http://mp3.ffh.de/ffhchannels/hq90er.mp3?amsparams=playerid:RTFFHTunein;skey:1581676248",
            active: false,
        },
        {
            name:"Sunshine Live",
            artist: "Electronic",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "http://sunshinelive.hoerradar.de/sunshinelive-live-mp3-hq?sABC=5r46783o%230%231o70r21o79929956s30p83402120q5q4%23gharva&amsparams=playerid:tunein;skey:1581676603",
            active: false,
        },
        {
            name:"Indie 88",
            artist: "Indie",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "http://cob-ais.leanstream.co/CINDFM-MP3?args=tunein_01",
            active: false,
        },
        {
            name:"That Christmas Channel",
            artist: "Christmas",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://los.cdnstream.com/1102_128",
            active: false,
        },
        {
            name:"Fun Kids",
            artist: "Kids",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://listen-funkids.sharp-stream.com/funkids.mp3?device=tunein",
            active: false,
        },
        {
            name:"Costa del Mar",
            artist: "Lounge",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://stream.cdm-chillout.com:8020/stream-mp3-Chill",
            active: false,
        },
        {
            name:"La Z Latina",
            artist: "Latin Music",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://playerservices.streamtheworld.com/api/livestream-redirect/XEQR_FM.mp3?tdtok=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImZTeXA4In0.eyJpc3MiOiJ0aXNydiIsInN1YiI6IjIxMDY0IiwiaWF0IjoxNTgxNjc3NjI5LCJ0ZC1yZWciOmZhbHNlfQ.OMSwENr75iagPVR3nvwThrfNUw1lLuC7x1jCWc5qOAo",
            active: false,
        },
        {
            name:"Soundstorm Relax",
            artist: "Relax",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://stream.soundstorm-radio.com:8000/stream1",
            active: false,
        },
        {
            name:"Defjay Radio",
            artist: "70's",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },
        {
            name:"R&B",
            artist: "80's",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://pool.defjay.com/DEFJAY.mp3",
            active: false,
        },
        {
            name:"1.FM Reggae Trade",
            artist: "Reggae",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://strm112.1.fm/reggae_mobile_mp3",
            active: false,
        },
        {
            name:"Bandit Rock",
            artist: "Rock",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://fm02-ice.stream.khz.se/fm02_mp3",
            active: false,
        },
        {
            name:"Classical MPR",
            artist: "Classic",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cms.stream.publicradio.org/cms.mp3?aw_0_1st.playerid=RadioTime&aw_0_1st.skey=1582304573&aw_0_1st.platform=tunein",
            active: false,
        },
        {
            name:"Amazing Blues",
            artist: "Blues",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://mainstream.amazingradios.com:8000/blues128",
            active: false,
        },
        {
            name:"ABC Jazz",
            artist: "Jazz",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://live-radio02.mediahubaustralia.com/JAZW/mp3/",
            active: false,
        },
        {
            name:"Hits for Kids",
            artist: "Kids",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
    ];
}

export default chillHop;
